on: [ pull_request, push ]
name: ci
jobs:
  check-pr:
    name: validate commits
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0
    - run: git fetch origin master
    - uses: flux-framework/pr-validator@master

  checkpatch:
    name: kernel style check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0
    - name: check style
      run: make -C driver check

  build-driver-5-4:
    name: build driver against linux-5.4
    runs-on: ubuntu-20.04
    steps:
    - name: install libelf-dev
      run: sudo apt-get -y install libelf-dev
    - name: install linux-headers
      run: sudo apt-get install linux-headers-5.4.0-52-generic
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0
    - name: build driver
      run: KERNEL_VERSION=5.4.0-52-generic make -C driver

  build-driver-4-15:
    name: build driver against linux-4.15
    runs-on: ubuntu-18.04
    steps:
    - name: install libelf-dev
      run: sudo apt-get -y install libelf-dev
    - name: install linux-headers
      run: sudo apt-get install linux-headers-4.15.0-106-generic
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0
    - name: build driver
      run: KERNEL_VERSION=4.15.0-106-generic make -C driver

  build-load-latest:
    name: build and load driver against running kernel
    runs-on: ubuntu-latest
    steps:
    - name: install libelf-dev
      run: sudo apt-get -y install libelf-dev
    - name: install linux-headers
      run: sudo apt-get install linux-headers-$(uname -r)
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0
    - name: build driver
      run: make -C driver
    - name: clear kernel log messages
      run: sudo dmesg --clear
    - name: load dependent kernel modules
      run: sudo modprobe parport
    - name: load driver
      run: sudo insmod driver/sbiglpt.ko \
    - name: print kernel log messages
      if: always()
      run: sudo dmesg
    - name: unload kernel modules
      if: always()
      run: sudo rmmod sbiglpt parport

